### ISSUE TITLE
Copy Existing DMP selection needs a search function

### ISSUE THREAD

**Issue by atmickle** [CDLUC3/dmptool_v2#136]
Currently you have to page through the DMPs in a predefined order to select the one you want to copy. Can we add the same search function that is available in the Public DMPs lookup?

**Comment by stephaniesimms** [comment]
DataONE Usability testing (May 2014) noted same issue:
Provide a way to sort or search existing DMPs, either by selecting table column headings (name, owner) or inserting a sort/search box. Users also requested to see funding agency in the existing DMP table.

**Comment by stephaniesimms** [comment]
Kris Bolt from Harvard: It is tedious to scroll through long lists of templates, existing DMPs, etc. within the tool. A desired enhancement for these lists is the ability to search and/or sort.

**Comment by atmickle** [comment]
I think this is fixed in the latest version.

**Comment by stephaniesimms** [comment]
yes it is. and we'll be improving the search and sort functionality for all tables soon. I also wanted to note that this is now a legacy/inactive repo. you can report any new issues here https://github.com/CDLUC3/dmptool/issues
